<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_brand_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
=======
# Generated by Django 5.1.4 on 2025-01-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_brand_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
>>>>>>> 235f43ea45fb7904dfdbcdba5ee43e48947246b1
