# Generated by Django 5.1.4 on 2025-01-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_products_brand_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='product_category',
        ),
    ]
