<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_products_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.create_seller_account'),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 5.1.4 on 2025-01-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_products_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.create_seller_account'),
            preserve_default=False,
        ),
    ]
>>>>>>> 235f43ea45fb7904dfdbcdba5ee43e48947246b1
