# Generated by Django 5.1.4 on 2025-01-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_products_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_seller_account',
            name='facebook_page',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='create_seller_account',
            name='instagram_page',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
